import { env } from '../../../config/env';
import { BaseHttpAdapter } from './baseHttp.adapter';
import { DhanInstrument, resolveDhanSecurityId, toDhanExchangeSegment } from './instrumentResolver';
import {
  BrokerAdapter,
  BrokerCredentials,
  BrokerProfile,
  Candle,
  Funds,
  HistoricalDataParams,
  Holding,
  ModifyOrderRequest,
  Order,
  OrderRequest,
  OrderResponse,
  OrderStatus,
  Position,
  Quote,
} from './brokerAdapter.interface';

const SCRIP_MASTER_URL = 'https://images.dhan.co/api-data/api-scrip-master.csv';

/** Dhan's intraday endpoint only supports these minute granularities; anything else falls back to the nearest supported one. */
const DHAN_INTRADAY_INTERVAL: Record<Exclude<HistoricalDataParams['timeframe'], '1d'>, string> = {
  '1m': '1',
  '3m': '5', // Dhan has no 3-minute bucket — 5-minute is the closest supported interval.
  '5m': '5',
  '15m': '15',
  '30m': '25', // closest supported bucket to 30m
  '1h': '60',
};

/**
 * Dhan uses a long-lived "access token" generated from the Dhan web console
 * (Profile → DhanHQ Trading APIs) rather than a redirect OAuth dance.
 * The user pastes their `clientId` + `accessToken` (and optionally `apiKey`
 * if using partner API) into our "Connect Dhan" form; we never see their
 * Dhan login password/OTP.
 *
 * Docs: https://dhanhq.co/docs/v2/
 */
export class DhanAdapter extends BaseHttpAdapter implements BrokerAdapter {
  public readonly brokerName = 'dhan';
  protected baseUrl = env.brokers.dhan.baseUrl;

  private accessToken: string;
  private clientId: string;

  constructor(accessToken: string, clientId: string) {
    super();
    this.accessToken = accessToken;
    this.clientId = clientId;
  }

  private authHeaders() {
    return {
      'access-token': this.accessToken,
      'client-id': this.clientId,
    };
  }

  async connect(credentials: BrokerCredentials) {
    // Dhan's token is generated by the user on their own dashboard, so
    // "connecting" here just validates it works by fetching the profile.
    this.accessToken = String(credentials.accessToken || '');
    this.clientId = String(credentials.clientId || '');
    const profile = await this.getProfile();
    return { accessToken: this.accessToken, profile };
  }

  async getProfile(): Promise<BrokerProfile> {
    const data = await this.request<any>('/v2/profile', { headers: this.authHeaders() });
    // Dhan's /v2/profile response has no separate display-name field — just
    // dhanClientId, tokenValidity, activeSegment, etc — so the client id
    // doubles as the name here (previously this was a no-op ternary that
    // always evaluated to the same thing).
    return {
      clientId: data.dhanClientId || this.clientId,
      name: data.dhanClientId || this.clientId,
      broker: this.brokerName,
    };
  }

  async getFunds(): Promise<Funds> {
    const data = await this.request<any>('/v2/fundlimit', { headers: this.authHeaders() });
    return {
      availableBalance: Number(data.availabelBalance ?? data.availableBalance ?? 0),
      usedMargin: Number(data.utilizedAmount ?? 0),
      totalBalance: Number(data.sodLimit ?? 0),
      collateral: Number(data.collateralAmount ?? 0),
      raw: data,
    };
  }

  async getPositions(): Promise<Position[]> {
    const data = await this.request<any[]>('/v2/positions', { headers: this.authHeaders() });
    return (data || []).map((p) => ({
      tradingSymbol: p.tradingSymbol,
      exchange: p.exchangeSegment,
      segment: mapDhanSegment(p.exchangeSegment),
      productType: p.productType,
      quantity: Number(p.netQty ?? 0),
      averagePrice: Number(p.costPrice ?? 0),
      // Dhan's /v2/positions response has no LTP field at all — it's
      // intentionally left out (Dhan's own guidance is to source LTP from
      // the marketfeed/websocket APIs instead), so there's nothing to read
      // here rather than a wrong field name.
      lastTradedPrice: undefined,
      realizedPnl: Number(p.realizedProfit ?? 0),
      unrealizedPnl: Number(p.unrealizedProfit ?? 0),
      raw: p,
    }));
  }

  async getOrders(): Promise<Order[]> {
    const data = await this.request<any[]>('/v2/orders', { headers: this.authHeaders() });
    return (data || []).map(mapDhanOrder);
  }

  /**
   * Docs: GET /v2/holdings — the `exchange` field is literally the string
   * "ALL" for every row (Dhan's holdings view isn't exchange-scoped), so
   * there's no real per-symbol exchange to read; defaults to 'NSE' since
   * that's where the overwhelming majority of demat equity holdings are
   * listed. No LTP field either — same as /v2/positions, source live price
   * from the feed service instead.
   */
  async getHoldings(): Promise<Holding[]> {
    const data = await this.request<any[]>('/v2/holdings', { headers: this.authHeaders() });
    return (data || []).map((h) => ({
      tradingSymbol: h.tradingSymbol,
      isin: h.isin,
      exchange: 'NSE',
      quantity: Number(h.totalQty ?? 0),
      averagePrice: Number(h.avgCostPrice ?? 0),
      lastTradedPrice: undefined,
      raw: h,
    }));
  }

  private async resolveInstrument(exchange: string, tradingSymbol: string): Promise<DhanInstrument> {
    return resolveDhanSecurityId(exchange, tradingSymbol, undefined, () =>
      this.requestText(SCRIP_MASTER_URL),
    );
  }

  async placeOrder(order: OrderRequest): Promise<OrderResponse> {
    // Dhan's order API identifies the instrument by `securityId` + the
    // segment-qualified `exchangeSegment` enum (e.g. "NSE_EQ"), not by
    // trading symbol / plain exchange — this previously sent `tradingSymbol`
    // and the raw `exchange` string, which Dhan's API silently rejects.
    const instrument = await this.resolveInstrument(order.exchange, order.tradingSymbol);
    const payload = {
      dhanClientId: this.clientId,
      transactionType: order.side,
      exchangeSegment: instrument.exchangeSegment,
      productType: order.productType,
      orderType: order.orderType,
      quantity: order.quantity,
      price: order.price ?? 0,
      triggerPrice: order.triggerPrice ?? 0,
      securityId: instrument.securityId,
      validity: 'DAY',
    };
    const data = await this.request<any>('/v2/orders', {
      method: 'POST',
      headers: this.authHeaders(),
      body: payload,
    });
    return { brokerOrderId: data.orderId, status: data.orderStatus, raw: data };
  }

  async modifyOrder(orderId: string, order: ModifyOrderRequest): Promise<OrderResponse> {
    const data = await this.request<any>(`/v2/orders/${orderId}`, {
      method: 'PUT',
      headers: this.authHeaders(),
      body: {
        dhanClientId: this.clientId,
        orderId,
        quantity: order.quantity,
        price: order.price,
        triggerPrice: order.triggerPrice,
        orderType: order.orderType,
        // Dhan's modify-order request always echoes a validity, same as
        // the original place-order call — every documented example
        // includes it and omitting it was untested against the live API.
        validity: 'DAY',
      },
    });
    return { brokerOrderId: orderId, status: data.orderStatus, raw: data };
  }

  async cancelOrder(orderId: string): Promise<OrderResponse> {
    const data = await this.request<any>(`/v2/orders/${orderId}`, {
      method: 'DELETE',
      headers: this.authHeaders(),
    });
    return { brokerOrderId: orderId, status: data.orderStatus ?? 'CANCELLED', raw: data };
  }

  async getOrderStatus(orderId: string): Promise<OrderStatus> {
    const data = await this.request<any>(`/v2/orders/${orderId}`, { headers: this.authHeaders() });
    return {
      brokerOrderId: orderId,
      status: data.orderStatus,
      filledQuantity: Number(data.filledQty ?? 0),
      averagePrice: Number(data.averageTradedPrice ?? 0),
      raw: data,
    };
  }

  async getQuote(symbol: string, exchange = 'NSE'): Promise<Quote> {
    // The marketfeed LTP API keys its response by numeric securityId, not
    // trading symbol — this previously sent the trading symbol as both the
    // request and lookup key, which never matches Dhan's response shape.
    const instrument = await this.resolveInstrument(exchange, symbol);
    const data = await this.request<any>('/v2/marketfeed/ltp', {
      method: 'POST',
      headers: this.authHeaders(),
      body: { [instrument.exchangeSegment]: [Number(instrument.securityId)] },
    });
    const ltp = data?.data?.[instrument.exchangeSegment]?.[instrument.securityId]?.last_price;
    return { tradingSymbol: symbol, ltp: Number(ltp ?? 0), raw: data };
  }

  async getHistoricalData(params: HistoricalDataParams): Promise<Candle[]> {
    const instrument = await resolveDhanSecurityId(params.exchange, params.tradingSymbol, params.segment, () =>
      this.requestText(SCRIP_MASTER_URL),
    );
    const instrumentType = params.segment === 'fno' ? 'FUTSTK' : 'EQUITY';
    const pad = (n: number) => String(n).padStart(2, '0');
    const toDateStr = (d: Date) => `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}`;
    const toDateTimeStr = (d: Date) =>
      `${toDateStr(d)} ${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}`;

    let data: any;
    if (params.timeframe === '1d') {
      data = await this.request<any>('/v2/charts/historical', {
        method: 'POST',
        headers: this.authHeaders(),
        body: {
          securityId: instrument.securityId,
          exchangeSegment: instrument.exchangeSegment,
          instrument: instrumentType,
          expiryCode: 0,
          oi: false,
          fromDate: toDateStr(params.from),
          toDate: toDateStr(params.to),
        },
      });
    } else {
      data = await this.request<any>('/v2/charts/intraday', {
        method: 'POST',
        headers: this.authHeaders(),
        body: {
          securityId: instrument.securityId,
          exchangeSegment: instrument.exchangeSegment,
          instrument: instrumentType,
          interval: DHAN_INTRADAY_INTERVAL[params.timeframe],
          oi: false,
          fromDate: toDateTimeStr(params.from),
          toDate: toDateTimeStr(params.to),
        },
      });
    }

    // Response is parallel arrays: { open: [], high: [], low: [], close: [], volume: [], timestamp: [] }.
    const { open = [], high = [], low = [], close = [], volume = [], timestamp = [] } = data ?? {};
    const candles: Candle[] = [];
    for (let i = 0; i < timestamp.length; i++) {
      candles.push({
        timestamp: Number(timestamp[i]) * 1000, // Dhan returns epoch seconds
        open: Number(open[i]),
        high: Number(high[i]),
        low: Number(low[i]),
        close: Number(close[i]),
        volume: Number(volume[i] ?? 0),
      });
    }
    return candles;
  }
}

function mapDhanSegment(exchangeSegment: string): Position['segment'] {
  if (!exchangeSegment) return 'equity';
  if (exchangeSegment.includes('FNO')) return 'fno';
  if (exchangeSegment.includes('CURRENCY')) return 'currency';
  if (exchangeSegment.includes('COMM')) return 'commodity';
  return 'equity';
}

function mapDhanOrder(o: any): Order {
  return {
    brokerOrderId: o.orderId,
    tradingSymbol: o.tradingSymbol,
    exchange: o.exchangeSegment,
    segment: mapDhanSegment(o.exchangeSegment),
    side: o.transactionType,
    orderType: o.orderType,
    productType: o.productType,
    quantity: Number(o.quantity ?? 0),
    filledQuantity: Number(o.filledQty ?? 0),
    price: Number(o.price ?? 0),
    triggerPrice: Number(o.triggerPrice ?? 0),
    averagePrice: Number(o.averageTradedPrice ?? 0),
    status: o.orderStatus,
    statusMessage: o.omsErrorDescription,
    placedAt: o.createTime,
    raw: o,
  };
}