import { env } from '../../../config/env';
import { BaseHttpAdapter } from './baseHttp.adapter';
import {
  BrokerAdapter,
  BrokerCredentials,
  BrokerProfile,
  Funds,
  ModifyOrderRequest,
  Order,
  OrderRequest,
  OrderResponse,
  OrderStatus,
  Position,
  Quote,
} from './brokerAdapter.interface';

/**
 * Dhan uses a long-lived "access token" generated from the Dhan web console
 * (Profile → DhanHQ Trading APIs) rather than a redirect OAuth dance.
 * The user pastes their `clientId` + `accessToken` (and optionally `apiKey`
 * if using partner API) into our "Connect Dhan" form; we never see their
 * Dhan login password/OTP.
 *
 * Docs: https://dhanhq.co/docs/v2/
 */
export class DhanAdapter extends BaseHttpAdapter implements BrokerAdapter {
  public readonly brokerName = 'dhan';
  protected baseUrl = env.brokers.dhan.baseUrl;

  private accessToken: string;
  private clientId: string;

  constructor(accessToken: string, clientId: string) {
    super();
    this.accessToken = accessToken;
    this.clientId = clientId;
  }

  private authHeaders() {
    return {
      'access-token': this.accessToken,
      'client-id': this.clientId,
    };
  }

  async connect(credentials: BrokerCredentials) {
    // Dhan's token is generated by the user on their own dashboard, so
    // "connecting" here just validates it works by fetching the profile.
    this.accessToken = String(credentials.accessToken || '');
    this.clientId = String(credentials.clientId || '');
    const profile = await this.getProfile();
    return { accessToken: this.accessToken, profile };
  }

  async getProfile(): Promise<BrokerProfile> {
    const data = await this.request<any>('/v2/profile', { headers: this.authHeaders() });
    return {
      clientId: data.dhanClientId || this.clientId,
      name: data.tokenValidity ? data.dhanClientId : data.dhanClientId,
      broker: this.brokerName,
    };
  }

  async getFunds(): Promise<Funds> {
    const data = await this.request<any>('/v2/fundlimit', { headers: this.authHeaders() });
    return {
      availableBalance: Number(data.availabelBalance ?? data.availableBalance ?? 0),
      usedMargin: Number(data.utilizedAmount ?? 0),
      totalBalance: Number(data.sodLimit ?? 0),
      collateral: Number(data.collateralAmount ?? 0),
      raw: data,
    };
  }

  async getPositions(): Promise<Position[]> {
    const data = await this.request<any[]>('/v2/positions', { headers: this.authHeaders() });
    return (data || []).map((p) => ({
      tradingSymbol: p.tradingSymbol,
      exchange: p.exchangeSegment,
      segment: mapDhanSegment(p.exchangeSegment),
      productType: p.productType,
      quantity: Number(p.netQty ?? 0),
      averagePrice: Number(p.costPrice ?? 0),
      lastTradedPrice: Number(p.lastTradedPrice ?? 0),
      realizedPnl: Number(p.realizedProfit ?? 0),
      unrealizedPnl: Number(p.unrealizedProfit ?? 0),
      raw: p,
    }));
  }

  async getOrders(): Promise<Order[]> {
    const data = await this.request<any[]>('/v2/orders', { headers: this.authHeaders() });
    return (data || []).map(mapDhanOrder);
  }

  async placeOrder(order: OrderRequest): Promise<OrderResponse> {
    const payload = {
      dhanClientId: this.clientId,
      transactionType: order.side,
      exchangeSegment: order.exchange,
      productType: order.productType,
      orderType: order.orderType,
      quantity: order.quantity,
      price: order.price ?? 0,
      triggerPrice: order.triggerPrice ?? 0,
      tradingSymbol: order.tradingSymbol,
      validity: 'DAY',
    };
    const data = await this.request<any>('/v2/orders', {
      method: 'POST',
      headers: this.authHeaders(),
      body: payload,
    });
    return { brokerOrderId: data.orderId, status: data.orderStatus, raw: data };
  }

  async modifyOrder(orderId: string, order: ModifyOrderRequest): Promise<OrderResponse> {
    const data = await this.request<any>(`/v2/orders/${orderId}`, {
      method: 'PUT',
      headers: this.authHeaders(),
      body: {
        dhanClientId: this.clientId,
        orderId,
        quantity: order.quantity,
        price: order.price,
        triggerPrice: order.triggerPrice,
        orderType: order.orderType,
      },
    });
    return { brokerOrderId: orderId, status: data.orderStatus, raw: data };
  }

  async cancelOrder(orderId: string): Promise<OrderResponse> {
    const data = await this.request<any>(`/v2/orders/${orderId}`, {
      method: 'DELETE',
      headers: this.authHeaders(),
    });
    return { brokerOrderId: orderId, status: data.orderStatus ?? 'CANCELLED', raw: data };
  }

  async getOrderStatus(orderId: string): Promise<OrderStatus> {
    const data = await this.request<any>(`/v2/orders/${orderId}`, { headers: this.authHeaders() });
    return {
      brokerOrderId: orderId,
      status: data.orderStatus,
      filledQuantity: Number(data.filledQty ?? 0),
      averagePrice: Number(data.averageTradedPrice ?? 0),
      raw: data,
    };
  }

  async getQuote(symbol: string): Promise<Quote> {
    const data = await this.request<any>('/v2/marketfeed/ltp', {
      method: 'POST',
      headers: this.authHeaders(),
      body: { NSE_EQ: [symbol] },
    });
    return { tradingSymbol: symbol, ltp: Number(data?.data?.NSE_EQ?.[symbol]?.last_price ?? 0), raw: data };
  }
}

function mapDhanSegment(exchangeSegment: string): Position['segment'] {
  if (!exchangeSegment) return 'equity';
  if (exchangeSegment.includes('FNO')) return 'fno';
  if (exchangeSegment.includes('CURRENCY')) return 'currency';
  if (exchangeSegment.includes('COMM')) return 'commodity';
  return 'equity';
}

function mapDhanOrder(o: any): Order {
  return {
    brokerOrderId: o.orderId,
    tradingSymbol: o.tradingSymbol,
    exchange: o.exchangeSegment,
    segment: mapDhanSegment(o.exchangeSegment),
    side: o.transactionType,
    orderType: o.orderType,
    productType: o.productType,
    quantity: Number(o.quantity ?? 0),
    filledQuantity: Number(o.filledQty ?? 0),
    price: Number(o.price ?? 0),
    triggerPrice: Number(o.triggerPrice ?? 0),
    averagePrice: Number(o.averageTradedPrice ?? 0),
    status: o.orderStatus,
    statusMessage: o.omsErrorDescription,
    placedAt: o.createTime,
    raw: o,
  };
}
